# Generated by Django 4.0.4 on 2022-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=9371654426, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.CharField(default='images/profile_pic', max_length=255),
        ),
    ]
